29 rating edition
WildCodeSchool/lille-js-202003-project-literate-guide-frontend pull request #11
Opened 2020-07-02 19:17 UTC by MaximePikss

2020-07-02 20:31 UTC, RoxaneDrelon submitted a review, later dismissed
SnE, waiting for Loïc to see the "no-console: false"

2020-07-06 07:56 UTC, LoicBrassart requested changes
Some dead code

2020-07-06 07:56 UTC, LoicBrassart commented on src/components/capsulelist/CapsuleList.jsx
> +//   );
Dead code

2020-07-06 08:16 UTC, RoxaneDrelon requested changes
ESLint, problème Capsule/CapsuleList

2020-07-06 09:54 UTC, RoxaneDrelon approved these changes
SnE, "test" is normal

2020-07-06 13:41 UTC, LoicBrassart approved these changes
SnE

2020-07-06 13:53 UTC, merged