08 capsule display info
WildCodeSchool/lille-js-202003-project-literate-guide-frontend pull request #20
Opened 2020-07-15 15:46 UTC by MaximePikss

2020-07-16 08:50 UTC, RoxaneDrelon submitted a review, later dismissed
SnE

2020-07-16 19:22 UTC, LoicBrassart requested changes
One minor Evil

2020-07-16 19:22 UTC, LoicBrassart commented on src/components/capsulefull/CapsuleFull.jsx
> +    <>
Useless Fragment, isn't it ?

2020-07-17 06:57 UTC, RoxaneDrelon approved these changes
SnE

2020-07-17 07:09 UTC, LoicBrassart approved these changes
SnE

2020-07-17 07:09 UTC, merged