37 course display
WildCodeSchool/lille-js-202003-project-literate-guide-frontend pull request #24
Opened 2020-07-21 14:29 UTC by llaulier

2020-07-21 15:54 UTC, RoxaneDrelon commented on src/components/coursedisplay/CourseDisplayTag.jsx
> +              color="primary"
Bad, never used

2020-07-21 15:55 UTC, RoxaneDrelon requested changes
Bad unused component

2020-07-21 15:56 UTC, LoicBrassart submitted a review, later dismissed
SnE

2020-07-21 16:04 UTC, RoxaneDrelon approved these changes
SnE

2020-07-22 09:07 UTC, LoicBrassart approved these changes
SnE

2020-07-22 09:08 UTC, merged